services:
  imageblog:
    build: .
    volumes:
      - .:/usr/src/app
    expose:
      - 80
    environment:
      VIRTUAL_HOST: xn--berblendet-8db.de, überblendet.de, www.überblendet.de, www.xn--berblendet-8db.de

networks:
  default:
      name: nginx-proxy