services:
  imageblog:
    build: .
    volumes:
      - .:/usr/src/app
    network_mode: bridge
    expose:
      - 80
    environment:
      VIRTUAL_HOST: xn--berblendet-8db.de, überblendet.de, www.überblendet.de